#spring.data.mongodb.uri=mongodb+srv://sharmavn258_db_user:vanshsh12@cluster0.crl7ag1.mongodb.net/?appName=telusko1
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
#spring.data.mongodb.database=Journaldb;
#spring.data.mongodb.auto-index-creation=true
#spring.security.user.name=vansh
#spring.security.user.password=sharma

#spring.data.mongodb.uri=mongodb+srv://sharmavn258_db_user:vanshsh12@cluster0.crl7ag1.mongodb.net/telusko1?retryWrites=true&w=majority
#spring.data.mongodb.second.uri=mongodb+srv://sharmavn258_db_user:vanshsh12@cluster0.crl7ag1.mongodb.net/Project?retryWrites=true&w=majority

spring.data.mongodb.uri=mongodb+srv://sharmavn258_db_user:vanshsh12@cluster0.crl7ag1.mongodb.net/Project?retryWrites=true&w=majority
spring.data.mongodb.database=Project
